
cc_test(
    name = "test_bingoboard",
    srcs = ["test_bingoboard.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//days/d4:bingoboard"
        ],
    visibility = ["//visibility:public"],
)

